### ISSUE TITLE
Add Goals controller

### ISSUE THREAD

**Issue by marppasas** [marppasas/ygoal#15]
Create the model too. At first, the fields will be:
1. GoalID
2. UserID
3. Title
4. Description (optional)
6. Status (enum: created, in progress and done)
5. CreatedOn
7. ModifiedOn

When created, the initial status should be 'Created'. The 'In Progress' status means the user started working on complete it. Seems to be unnecessary, but can be helpful when there is a goal that is created but will be take a longer time to finish it. For example, save money for a trip.

**Comment by nicoovillarr** [comment]
Done in 12
